// Public exports for the produtos feature boundary.
export { default as ProductCard } from './components/ProductCard'
export { default as ProdutoModal } from './components/ProductModal'
export { default as ProductStats } from './components/ProductStats'
export { default as ProdutoTabela } from './components/ProductTable'
export { useProductModal } from './hooks/use-product-modal'
export { useProductModalStore } from './store/product-modal.store'
export { useProdutoMutations } from './hooks/useProdutoMutations'
export { useProdutos } from './hooks/useProdutos'
export type { CreateProdutoDTO, Produto } from './types'
